In [24]:
import plotly.express as px 

df = px.data.iris()

In [25]:
px.scatter(df, x="sepal_length", y="sepal_width", color="species")

In [26]:
px.scatter(df, x="petal_length", y="petal_width", color="species")

In [27]:
from sklearn.preprocessing import StandardScaler 

sc = StandardScaler()
standardised = sc.fit_transform(df.drop(["species", "species_id"], axis=1))

In [28]:
from sklearn.decomposition import PCA

pca = PCA()
pca.fit(standardised)

PCA()

In [29]:
import pandas as pd
pd.DataFrame(standardised).corr()

          0         1         2         3
0  1.000000 -0.109369  0.871754  0.817954
1 -0.109369  1.000000 -0.420516 -0.356544
2  0.871754 -0.420516  1.000000  0.962757
3  0.817954 -0.356544  0.962757  1.000000

In [30]:
pca.components_

array([[ 0.52237162, -0.26335492,  0.58125401,  0.56561105],
       [ 0.37231836,  0.92555649,  0.02109478,  0.06541577],
       [ 0.72101681, -0.24203288, -0.14089226, -0.6338014 ],
       [-0.26199559,  0.12413481,  0.80115427, -0.52354627]])

In [31]:
import numpy as np

In [32]:
pd.DataFrame(standardised@pca.components_.T)

            0         1         2         3
0   -2.264542  0.505704  0.121943 -0.023073
1   -2.086426 -0.655405  0.227251 -0.103208
2   -2.367950 -0.318477 -0.051480 -0.027825
3   -2.304197 -0.575368 -0.098860  0.066311
4   -2.388777  0.674767 -0.021428  0.037397
..        ...       ...       ...       ...
145  1.870522  0.382822 -0.254532 -0.388890
146  1.558492 -0.905314  0.025382 -0.221322
147  1.520845  0.266795 -0.179277 -0.118903
148  1.376391  1.016362 -0.931405 -0.024146
149  0.959299 -0.022284 -0.528794  0.163676

[150 rows x 4 columns]

In [33]:
pc_df

         PC_1      PC_2      PC_3      PC_4    species
0   -2.264542  0.505704  0.121943 -0.023073     setosa
1   -2.086426 -0.655405  0.227251 -0.103208     setosa
2   -2.367950 -0.318477 -0.051480 -0.027825     setosa
3   -2.304197 -0.575368 -0.098860  0.066311     setosa
4   -2.388777  0.674767 -0.021428  0.037397     setosa
..        ...       ...       ...       ...        ...
145  1.870522  0.382822 -0.254532 -0.388890  virginica
146  1.558492 -0.905314  0.025382 -0.221322  virginica
147  1.520845  0.266795 -0.179277 -0.118903  virginica
148  1.376391  1.016362 -0.931405 -0.024146  virginica
149  0.959299 -0.022284 -0.528794  0.163676  virginica

[150 rows x 5 columns]

In [34]:
# pd.DataFrame(standardised@pca.components_.T, columns=pc_df.columns[:4]).apply(lambda x: np.round(x, 4)).\
#   equals(pc_df.drop("species", axis=1).apply(lambda x:  np.round(x, 4)))

In [35]:
pca.explained_variance_

array([2.93035378, 0.92740362, 0.14834223, 0.02074601])

In [36]:
pca.singular_values_

array([20.89551896, 11.75513248,  4.7013819 ,  1.75816839])

In [37]:
pca.singular_values_ / pca.singular_values_.sum()

array([0.53427285, 0.30056435, 0.12020858, 0.04495421])

In [38]:
pc_df = pd.DataFrame(pca.transform(standardised))
pc_df = pc_df.rename(columns={i:f"PC_{i+1}" for i in pc_df.columns})

In [39]:
pca.explained_variance_

array([2.93035378, 0.92740362, 0.14834223, 0.02074601])

In [40]:
pca.explained_variance_[0] / pca.explained_variance_.sum()

np.float64(0.7277045209380132)

In [41]:
pca.explained_variance_ratio_

array([0.72770452, 0.23030523, 0.03683832, 0.00515193])

In [42]:
pc_df["species"] = df["species"]

In [43]:
px.scatter_3d(pc_df, x="PC_1", y="PC_2", z="PC_3", color="species")

In [44]:
target = "species_id"

X = df.drop(["species", target], axis=1)
y = df[target]

In [45]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=41) # fixer le random state permet la reproductibilité de l'expérience

In [46]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression()

In [47]:
lr.score(X_train, y_train), lr.score(X_test, y_test)

(0.9732142857142857, 0.9210526315789473)

In [48]:
# montecarlo

for random_state in range(20):
    X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=random_state) 
    lr = LogisticRegression(max_iter=500)
    lr.fit(X_train, y_train)
    print(lr.score(X_train, y_train), lr.score(X_test, y_test))

0.9821428571428571 0.9736842105263158
0.9821428571428571 0.9736842105263158
0.9732142857142857 0.9736842105263158
0.9732142857142857 0.9736842105263158
0.9910714285714286 0.9736842105263158

0.9821428571428571 0.9736842105263158
0.9642857142857143 0.9473684210526315
0.9910714285714286 0.8947368421052632
0.9732142857142857 0.9210526315789473
0.9642857142857143 1.0
0.9732142857142857 1.0
0.9732142857142857 0.9210526315789473
0.9732142857142857 0.9736842105263158
0.9553571428571429 0.9736842105263158
0.9732142857142857 0.9736842105263158
0.9821428571428571 1.0
0.9821428571428571 0.9210526315789473
0.9821428571428571 0.9736842105263158
0.9732142857142857 1.0
0.9642857142857143 0.9473684210526315

In [49]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer

In [50]:
quantitative_columns = X.select_dtypes(include="float").columns
qualitative_columns = X.select_dtypes(exclude="float").columns

quantitative_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="mean")),
    ("standard", StandardScaler())
])

qualitative_transfomer = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(drop="first"))
])

column_transformer = ColumnTransformer([
    ("quantitative", quantitative_transformer, quantitative_columns),
    ("qualitative", qualitative_transfomer, qualitative_columns)
])

In [51]:
X_train

     sepal_length  sepal_width  petal_length  petal_width
125           7.2          3.2           6.0          1.8
135           7.7          3.0           6.1          2.3
95            5.7          3.0           4.2          1.2
126           6.2          2.8           4.8          1.8
79            5.7          2.6           3.5          1.0
..            ...          ...           ...          ...
52            6.9          3.1           4.9          1.5
19            5.1          3.8           1.5          0.3
98            5.1          2.5           3.0          1.1
110           6.5          3.2           5.1          2.0
93            5.0          2.3           3.3          1.0

[112 rows x 4 columns]

In [52]:
column_transformer.fit(X_train)
X_train = column_transformer.transform(X_train)
X_test = column_transformer.transform(X_test)

In [53]:
X_train

array([[ 1.53385453,  0.29782525,  1.21682331,  0.73049681],
       [ 2.13076804, -0.15911212,  1.27304617,  1.37879826],
       [-0.25688599, -0.15911212,  0.20481184, -0.04746493],
       [ 0.34002752, -0.61604949,  0.542149  ,  0.73049681],
       [-0.25688599, -1.07298685, -0.18874817, -0.30678551],
       [ 0.93694103,  0.06935656,  0.99193188,  1.50845855],
       [ 0.93694103,  0.52629393,  1.04815473,  1.63811884],
       [ 0.57879292, -0.84451817,  0.8232633 ,  0.8601571 ],
       [-1.0925649 ,  0.9832313 , -1.2569825 , -0.82542667],
       [ 0.45941022,  0.75476262,  0.99193188,  1.50845855],
       [-0.6150341 ,  0.75476262, -1.20075964, -1.34406783],
       [-1.57009571,  0.29782525, -1.36942822, -1.34406783],
       [-1.0925649 ,  0.9832313 , -1.42565108, -1.21440754],
       [-0.01812059, -0.15911212,  0.20481184,  0.34151594],
       [ 0.10126211, -0.3875808 ,  0.37348042,  0.34151594],
       [-1.80886111, -0.15911212, -1.42565108, -1.34406783],
       [-1.92824382, -0.15911212, -1.53809679, -1.47372812],
       [ 0.57879292,  0.29782525,  0.8232633 ,  1.37879826],
       [-1.57009571,  0.06935656, -1.31320536, -1.34406783],
       [ 0.10126211, -0.15911212,  0.542149  ,  0.73049681],
       [-0.4956514 ,  0.9832313 , -1.42565108, -1.34406783],
       [-0.4956514 ,  2.58251208, -1.36942822, -1.34406783],
       [ 1.41447183, -0.15911212,  1.16060045,  1.11947768],
       [ 0.45941022, -0.84451817,  0.59837186,  0.73049681],
       [ 2.36953345,  1.66863735,  1.44171475,  0.98981739],
       [-0.6150341 ,  1.89710603, -1.20075964, -1.08474725],
       [-0.9731822 ,  1.66863735, -1.2569825 , -1.34406783],
       [ 0.45941022, -0.3875808 ,  0.99193188,  0.73049681],
       [-0.8537995 ,  0.75476262, -1.36942822, -1.34406783],
       [ 1.77261994, -0.61604949,  1.27304617,  0.8601571 ],
       [ 0.93694103, -0.15911212,  0.65459472,  0.60083652],
       [ 0.45941022, -1.30145554,  0.65459472,  0.8601571 ],
       [-1.45071301,  0.29782525, -1.2569825 , -1.34406783],
       [-0.01812059,  0.29782525,  0.542149  ,  0.73049681],
       [ 1.65323724, -0.3875808 ,  1.38549189,  0.73049681],
       [ 0.93694103, -0.15911212,  0.76704044,  1.37879826],
       [ 0.45941022,  0.52629393,  1.21682331,  1.63811884],
       [-1.21194761,  0.06935656, -1.31320536, -1.47372812],
       [-1.0925649 ,  0.75476262, -1.2569825 , -1.08474725],
       [-0.25688599, -0.61604949,  0.14858899,  0.08219536],
       [ 0.93694103,  0.06935656,  0.31725756,  0.21185565],
       [ 1.17570643,  0.06935656,  0.71081758,  1.37879826],
       [-0.7344168 ,  1.44016867, -1.31320536, -1.34406783],
       [-1.68947841, -1.7583929 , -1.42565108, -1.21440754],
       [ 0.69817562, -0.15911212,  0.76704044,  0.98981739],
       [ 0.81755832, -0.3875808 ,  0.42970328,  0.08219536],
       [-0.13750329, -0.84451817,  0.14858899, -0.30678551],
       [-0.9731822 ,  1.44016867, -1.31320536, -1.08474725],
       [-0.9731822 ,  1.66863735, -1.08831392, -1.08474725],
       [ 0.45941022, -1.7583929 ,  0.31725756,  0.08219536],
       [ 1.17570643,  0.06935656,  0.87948616,  1.11947768],
       [ 0.22064481, -0.15911212,  0.59837186,  0.73049681],
       [ 2.13076804,  1.66863735,  1.61038333,  1.24913797],
       [-0.6150341 ,  0.75476262, -1.31320536, -1.08474725],
       [ 0.22064481, -0.3875808 ,  0.48592614,  0.21185565],
       [ 0.93694103,  0.52629393,  1.04815473,  1.11947768],
       [-0.9731822 ,  0.9832313 , -1.36942822, -1.34406783],
       [ 1.17570643,  0.29782525,  1.04815473,  1.37879826],
       [ 0.10126211, -1.98686159,  0.09236613, -0.30678551],
       [-0.01812059, -0.15911212,  0.71081758,  0.73049681],
       [-1.33133031,  0.75476262, -1.2569825 , -1.34406783],
       [ 0.57879292, -0.61604949,  0.99193188,  1.24913797],
       [ 2.13076804, -0.61604949,  1.61038333,  0.98981739],
       [ 0.22064481, -0.15911212,  0.42970328,  0.21185565],
       [ 0.57879292,  0.29782525,  0.37348042,  0.34151594],
       [-1.0925649 , -0.15911212, -1.2569825 , -1.34406783],
       [ 2.13076804, -1.07298685,  1.72282905,  1.37879826],
       [ 0.34002752,  0.75476262,  0.87948616,  1.37879826],
       [-0.9731822 ,  0.9832313 , -1.36942822, -1.21440754],
       [-0.6150341 , -0.15911212,  0.37348042,  0.34151594],
       [-1.33133031, -0.15911212, -1.36942822, -1.21440754],
       [ 0.69817562, -0.15911212,  0.93570902,  0.73049681],
       [ 0.10126211, -0.84451817,  0.71081758,  0.47117623],
       [-1.33133031, -0.15911212, -1.36942822, -1.47372812],
       [ 0.57879292, -0.61604949,  0.99193188,  1.11947768],
       [-0.13750329, -1.07298685,  0.09236613, -0.04746493],
       [ 0.69817562, -0.61604949,  0.42970328,  0.34151594],
       [ 0.34002752, -1.98686159,  0.37348042,  0.34151594],
       [-1.0925649 ,  0.52629393, -1.36942822, -1.34406783],
       [-0.8537995 ,  2.3540434 , -1.31320536, -1.47372812],
       [-0.37626869, -1.30145554,  0.03614327, -0.17712522],
       [ 1.53385453, -0.15911212,  1.10437759,  0.47117623],
       [-1.0925649 , -2.44379895, -0.18874817, -0.30678551],
       [ 0.69817562, -0.15911212,  1.10437759,  1.24913797],
       [-0.25688599, -0.61604949,  0.37348042,  0.08219536],
       [-1.21194761, -1.52992422, -0.30119389, -0.30678551],
       [-1.0925649 ,  0.29782525, -1.48187394, -1.34406783],
       [-0.4956514 , -1.7583929 ,  0.09236613,  0.08219536],
       [ 1.05632373,  0.29782525,  1.16060045,  1.37879826],
       [-0.25688599, -1.30145554,  0.65459472,  0.98981739],
       [-0.4956514 , -1.52992422, -0.07630245, -0.30678551],
       [-0.13750329, -0.84451817,  0.71081758,  0.8601571 ],
       [ 0.10126211,  0.75476262,  0.37348042,  0.47117623],
       [-1.0925649 ,  1.21169998, -1.36942822, -1.34406783],
       [-1.21194761,  0.06935656, -1.31320536, -1.47372812],
       [ 0.22064481, -0.61604949,  0.09236613,  0.08219536],
       [-0.9731822 ,  0.75476262, -1.31320536, -1.34406783],
       [-0.25688599,  3.03944945, -1.31320536, -1.08474725],
       [ 0.93694103, -1.30145554,  1.10437759,  0.73049681],
       [ 1.29508913,  0.29782525,  0.48592614,  0.21185565],
       [ 0.93694103,  0.06935656,  0.48592614,  0.34151594],
       [-0.6150341 ,  1.44016867, -1.31320536, -1.34406783],
       [ 0.34002752, -0.3875808 ,  0.2610347 ,  0.08219536],
       [ 0.45941022, -0.61604949,  0.71081758,  0.34151594],
       [-1.57009571,  1.21169998, -1.59431965, -1.34406783],
       [-0.37626869, -0.15911212,  0.37348042,  0.34151594],
       [ 0.57879292, -0.3875808 ,  0.2610347 ,  0.08219536],
       [ 1.17570643,  0.06935656,  0.59837186,  0.34151594],
       [-0.9731822 ,  1.66863735, -1.31320536, -1.21440754],
       [-0.9731822 , -1.30145554, -0.46986247, -0.17712522],
       [ 0.69817562,  0.29782525,  0.71081758,  0.98981739],
       [-1.0925649 , -1.7583929 , -0.30119389, -0.30678551]])

In [54]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=41) # fixer le random state permet la reproductibilité de l'expérience

quantitative_columns = X.select_dtypes(include="float").columns
qualitative_columns = X.select_dtypes(exclude="float").columns

quantitative_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="mean")),
    ("standard", StandardScaler())
])

qualitative_transfomer = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(drop="first"))
])

column_transformer = ColumnTransformer([
    ("quantitative", quantitative_transformer, quantitative_columns),
    ("qualitative", qualitative_transfomer, qualitative_columns)
])

column_transformer.fit(X_train)
# On ne fit jamais sur le test !!!!!
X_train = column_transformer.transform(X_train)
X_test = column_transformer.transform(X_test)

In [55]:
from sklearn.base import BaseEstimator, TransformerMixin

In [60]:
class SigmaClipper(BaseEstimator, TransformerMixin):
    def __init__(self, n_sigma=3.0):
        self.n_sigma = n_sigma 

    def fit(self, X, y=None):
        X_arr = np.asarray(X, dtype=float)
        if hasattr(X, "columns"):
            self.feature_names_in_ = np.asarray(X.columns, dtype=object)
        self.n_features_in_ = X_arr.shape[1]
        self.mean_ = X_arr.mean(axis=0)
        self.std_ = X_arr.std(axis=0)
        self.lower_ = self.mean_ - self.n_sigma * self.std_
        self.upper_ = self.mean_ + self.n_sigma * self.std_
        return self

    def transform(self, X):
        X_arr = np.asarray(X, dtype=float)
        if X_arr.shape[1] != self.n_features_in_:
            raise ValueError(
                f"{X_arr.shape[1]} colonnes reçues, {self.n_features_in_} attendues"
            )
        return np.clip(X_arr, self.lower_, self.upper_)

    def get_feature_names_out(self, input_features=None):
            if input_features is not None:
                return np.asarray(input_features, dtype=object)
            if hasattr(self, "feature_names_in_"):
                return self.feature_names_in_
            return np.asarray([f"x{i}" for i in range(self.n_features_in_)], dtype=object)

In [61]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=41) # fixer le random state permet la reproductibilité de l'expérience

quantitative_columns = X.select_dtypes(include="float").columns
qualitative_columns = X.select_dtypes(exclude="float").columns

quantitative_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="mean")),
    ("standard", StandardScaler()),
    ("clipper", SigmaClipper(n_sigma=3.0))
])

qualitative_transfomer = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(drop="first"))
])

column_transformer = ColumnTransformer([
    ("quantitative", quantitative_transformer, quantitative_columns),
    ("qualitative", qualitative_transfomer, qualitative_columns)
])

column_transformer.fit(X_train)
X_train = column_transformer.transform(X_train)
X_test = column_transformer.transform(X_test)

In [68]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=41) # fixer le random state permet la reproductibilité de l'expérience

quantitative_columns = X.select_dtypes(include="float").columns
qualitative_columns = X.select_dtypes(exclude="float").columns

quantitative_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="mean")),
    ("standard", StandardScaler()),
    ("clipper", SigmaClipper(n_sigma=3.0))
])

qualitative_transfomer = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(drop="first"))
])

column_transformer = ColumnTransformer([
    ("quantitative", quantitative_transformer, quantitative_columns),
    ("qualitative", qualitative_transfomer, qualitative_columns)
])

In [69]:
from sklearn.model_selection import GridSearchCV

In [77]:
model = Pipeline([
    ("prep", column_transformer),
    ("clf", LogisticRegression(max_iter=1000)),
])

model.fit(X_train, y_train)
model.score(X_test, y_test)

grid = GridSearchCV(
    model,
    param_grid={
        "prep__quantitative__clipper__n_sigma": [1.5, 2.0, 2.5, 3.0, 5.0],
        "clf__C": [0.1, 1.0, 10.0],
    },
    cv=5,
)

grid.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('prep',
                                        ColumnTransformer(transformers=[('quantitative',
                                                                         Pipeline(steps=[('imputer',
                                                                                          SimpleImputer()),
                                                                                         ('standard',
                                                                                          StandardScaler()),
                                                                                         ('clipper',
                                                                                          SigmaClipper())]),
                                                                         Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='str')),
                                                                        ('qualitative',
                                                                         Pipeline(steps=[('imputer',
                                                                                          SimpleImputer(strategy='most_frequent')),
                                                                                         ('onehot',
                                                                                          OneHotEncoder(drop='first'))]),
                                                                         Index([], dtype='str'))])),
                                       ('clf',
                                        LogisticRegression(max_iter=1000))]),
             param_grid={'clf__C': [0.1, 1.0, 10.0],
                         'prep__quantitative__clipper__n_sigma': [1.5, 2.0, 2.5,
                                                                  3.0, 5.0]})

In [78]:
pd.DataFrame(grid.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_clf__C,param_prep__quantitative__clipper__n_sigma,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.035900,0.007764,0.013609,0.008599,0.1,1.5,"{'clf__C': 0.1, 'prep__quantitative__clipper__...",0.956522,0.913043,0.727273,1.0,0.954545,0.910277,0.095548,11
1,0.057880,0.024940,0.016400,0.008435,0.1,2.0,"{'clf__C': 0.1, 'prep__quantitative__clipper__...",0.956522,0.913043,0.727273,1.0,0.909091,0.901186,0.093032,12
2,0.044717,0.006555,0.011301,0.002045,0.1,2.5,"{'clf__C': 0.1, 'prep__quantitative__clipper__...",0.956522,0.913043,0.727273,1.0,0.909091,0.901186,0.093032,12
3,0.037933,0.005699,0.009937,0.002415,0.1,3.0,"{'clf__C': 0.1, 'prep__quantitative__clipper__...",0.956522,0.913043,0.727273,1.0,0.909091,0.901186,0.093032,12
4,0.030265,0.005095,0.009726,0.002375,0.1,5.0,"{'clf__C': 0.1, 'prep__quantitative__clipper__...",0.956522,0.913043,0.727273,1.0,0.909091,0.901186,0.093032,12
5,0.062993,0.018142,0.015218,0.009352,1.0,1.5,"{'clf__C': 1.0, 'prep__quantitative__clipper__...",0.956522,1.000000,0.863636,1.0,1.000000,0.964032,0.052947,6
6,0.081190,0.045607,0.014468,0.004688,1.0,2.0,"{'clf__C': 1.0, 'prep__quantitative__clipper__...",0.956522,1.000000,0.863636,1.0,1.000000,0.964032,0.052947,6
7,0.046627,0.011610,0.010771,0.001221,1.0,2.5,"{'clf__C': 1.0, 'prep__quantitative__clipper__...",0.956522,1.000000,0.863636,1.0,1.000000,0.964032,0.052947,6
8,0.068456,0.027057,0.016171,0.007953,1.0,3.0,"{'clf__C': 1.0, 'prep__quantitative__clipper__...",0.956522,1.000000,0.863636,1.0,1.000000,0.964032,0.052947,6
9,0.038961,0.016526,0.008485,0.002414,1.0,5.0,"{'clf__C': 1.0, 'prep__quantitative__clipper__...",0.956522,1.000000,0.863636,1.0,1.000000,0.964032,0.052947,6
10,0.064741,0.036289,0.014554,0.007692,10.0,1.5,"{'clf__C': 10.0, 'prep__quantitative__clipper_...",0.956522,1.000000,0.909091,1.0,1.000000,0.973123,0.036174,1
11,0.122138,0.036097,0.019636,0.006210,10.0,2.0,"{'clf__C': 10.0, 'prep__quantitative__clipper_...",0.956522,1.000000,0.909091,1.0,1.000000,0.973123,0.036174,1
12,0.092392,0.011151,0.010854,0.003230,10.0,2.5,"{'clf__C': 10.0, 'prep__quantitative__clipper_...",0.956522,1.000000,0.909091,1.0,1.000000,0.973123,0.036174,1
13,0.128275,0.034271,0.028454,0.003474,10.0,3.0,"{'clf__C': 10.0, 'prep__quantitative__clipper_...",0.956522,1.000000,0.909091,1.0,1.000000,0.973123,0.036174,1
14,0.091820,0.009358,0.013917,0.003246,10.0,5.0,"{'clf__C': 10.0, 'prep__quantitative__clipper_...",0.956522,1.000000,0.909091,1.0,1.000000,0.973123,0.036174,1

In [ ]:
to_pred = column_transformer.transform(["95655", ["sku_135454654", 'sku_135454654'], "21/08/96"])
model.predict(to_pred)